# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-22 00:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crack_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='egg',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='slug',
        ),
    ]
