# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-22 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crack_app', '0002_auto_20190322_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='egg',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='egg',
            name='title',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
