# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-22 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crack_app', '0004_auto_20190322_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=models.CharField(max_length=2048),
        ),
    ]
