# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-22 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crack_app', '0006_auto_20190322_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingrediants',
            field=models.CharField(max_length=512),
        ),
    ]
